# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terrarium < Formula
  desc "Create reusable Terraform templates and build powerful platforms"
  homepage "https://github.com/cldcvr/terrarium"
  version "0.7-beta"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cldcvr/terrarium/releases/download/v0.7-beta/terrarium-v0.7-beta-macos-arm64.tar.gz"
      sha256 "bf08292ea687b89c970d1388f58a75c32683e0ef9951af45471146e37894816b"

      def install
        bin.install "terrarium"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cldcvr/terrarium/releases/download/v0.7-beta/terrarium-v0.7-beta-macos-x86_64.tar.gz"
      sha256 "689489e7a4cf572594de22e79688041349bd2c8d4e53154a019e65b8d9a24516"

      def install
        bin.install "terrarium"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cldcvr/terrarium/releases/download/v0.7-beta/terrarium-v0.7-beta-linux-arm64.tar.gz"
      sha256 "e4c61592e67a9d29428bb42fd54f62340948b4c42f667519c6bbbd59a6d2aec7"

      def install
        bin.install "terrarium"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cldcvr/terrarium/releases/download/v0.7-beta/terrarium-v0.7-beta-linux-x86_64.tar.gz"
      sha256 "0d07baa14aa8ef702837402961bfc1774d7ad1b780a18a179057f6143f5e0e50"

      def install
        bin.install "terrarium"
      end
    end
  end

  test do
    system "#{bin}/terrarium", "version"
  end
end
