# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terrarium < Formula
  desc "Create reusable Terraform templates and build powerful platforms"
  homepage "https://github.com/cldcvr/terrarium"
  version "0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cldcvr/terrarium/releases/download/v0.8/terrarium-v0.8-macos-arm64.tar.gz"
      sha256 "a0a8503524933fe2cc200bd36381bcd591cf533726786ace26f71c73b9b9353d"

      def install
        bin.install "terrarium"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cldcvr/terrarium/releases/download/v0.8/terrarium-v0.8-macos-x86_64.tar.gz"
      sha256 "5f56e9fc69fae10f630390594eb9752ba1617d6be1f054b05a7013abce9e4780"

      def install
        bin.install "terrarium"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cldcvr/terrarium/releases/download/v0.8/terrarium-v0.8-linux-x86_64.tar.gz"
      sha256 "64ab1b3f10db015880466622917a7d24043e7e9b743f69e1c4a5006106f58b8e"

      def install
        bin.install "terrarium"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cldcvr/terrarium/releases/download/v0.8/terrarium-v0.8-linux-arm64.tar.gz"
      sha256 "916a3179b46523d373662dec80f9c7f84dfc9297e2da49a11104df538dd3a868"

      def install
        bin.install "terrarium"
      end
    end
  end

  test do
    system "#{bin}/terrarium", "version"
  end
end
