# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terrarium < Formula
  desc "Create reusable Terraform templates and build powerful platforms"
  homepage "https://github.com/cldcvr/terrarium"
  version "0.7-beta"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cldcvr/terrarium/releases/download/v0.7-beta/terrarium-v0.7-beta-macos-arm64.tar.gz"
      sha256 "0ef679ab3460222562cfd0032520ef4ae5435480798a8485cfc178077bb2884e"

      def install
        bin.install "terrarium"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cldcvr/terrarium/releases/download/v0.7-beta/terrarium-v0.7-beta-macos-x86_64.tar.gz"
      sha256 "4f587b78cf1ad7439a48070aba4f3ecd52e5207b6a3c018efdad1763df02ff0d"

      def install
        bin.install "terrarium"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cldcvr/terrarium/releases/download/v0.7-beta/terrarium-v0.7-beta-linux-arm64.tar.gz"
      sha256 "dd9267fe4b4258e996db2268f22efc9312c83d27cad91d74ed38fba53b450f3e"

      def install
        bin.install "terrarium"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cldcvr/terrarium/releases/download/v0.7-beta/terrarium-v0.7-beta-linux-x86_64.tar.gz"
      sha256 "4b6fecd582a70af893302026f58c83d1a325dac02297516fcedeb149467406b5"

      def install
        bin.install "terrarium"
      end
    end
  end

  test do
    system "#{bin}/terrarium", "version"
  end
end
